### ISSUE TITLE
Declared resources returns empty object

### ISSUE THREAD

**Issue by jamescanady** [scimmyjs/scimmy#50]
When calling SCIMMY.Resources.declared() the result is an empty object. 

```js
SCIMMY.Resources.declare(SCIMMY.Resources.User)
  .extend(SCIMMY.Schemas.EnterpriseUser, true)
  .basepath(ROUTE_PREFIX + '/v2/User')
  .ingress(async (resource, instance) => {
   ...
  })
  .egress(async (resource) => {
   ...
  })
  .degress(async (resource) => {
   ...
  });
SCIMMY.Resources.declare(SCIMMY.Resources.Group)
  .basepath(ROUTE_PREFIX + '/v2/Group')
  .ingress(async (resource, instance) => {
    ...
  })
  .egress(async (resource) => {
    ...
  })
  .degress(async (resource) => {
    ...
  });
```

Attempting to return the resources to the caller via
```js
const resources = SCIMMY.Resources.declared();
```

**Comment by sleelin** [comment]
Hi @jamescanady,
I haven't been able to reproduce this issue, and one of the unit tests for the `SCIMMY.Resources.declared()` method, which must pass before new versions are published, specifically checks that an object containing all declared resources by name is returned when the `declared` method is called without arguments.

Could you please provide a few more details about your environment? Specifically:
- Are you using the latest version of SCIMMY (v1.2.3)?
- Are you calling `SCIMMY.Resources.declared()` from the same file that you're declaring the resources?
- If so, does the call happen before or after the declarations?
- If not, does the file with the call execute before or after the file with the declarations?
- Are you using any form of code bundling or tree shaking tools like rollup or vite, and if so, do they produce CommonJS or ESM files in their generated output?
- Any other details that might help to determine the cause and reproduce the issue.

Thanks,
Sam

**Comment by jamescanady** [comment]
Thank you for your response Sam,

-  version 1.2.3
- The configuration is export via a static init function, as this is passing in logging plug additional data retrieval classes. (I'm now looking at switching this to using the ctx instead)
- All configuration happens upfront before any calls to Resources.declared() or Resources.<type>.read()
- ...
- I'm using esbuild that produces CommonJS bundle (esbuild src/index.ts --minify --bundle --platform=node --target=es2020 --outfile=dist/index.js)
- SCIMMY.Resources.Schema.declared() worked as expected and showed User and Group schema, as well as Config.get()



Of additional note, I attempted to switch from using the declared calls for both Schema and ResourceTypes to use their respective read() commands, but that caused Schemas as well as ServiceProviderConfig and ResourceType to fail with unknown function read() errors now.

Here's a repo that you can review that experiences these issues:

https://github.com/jamescanady/scimtest

**Comment by jamescanady** [comment]
Found the issue with not calling new on the object instances within the singleton class.

**Comment by sleelin** [comment]
Hi @jamescanady, thanks for following up.
Using the repo you linked I was able to get a better understanding of what's happening to cause this issue, albeit only after a fair bit of wrangling to appease TypeScript (types for express, cors, and compression were missing from devDependencies, amongst other assorted typing complaints it had).

Firstly, it's worth noting that SCIMMY is exported as a _singleton_, so declared resources persist across any location it is imported from. This means that instead of returning SCIMMY from your initialisation method and assigning it to a constant, you can safely import the module instead (which will be far less confusing for TypeScript).

Second, to address the issue you originally raised. The `declared` method of `SCIMMY.Resources`, when called without arguments, returns an object whose keys/values are each declared resource name and the corresponding resource class. Since the resource classes don't explicitly define a `toJSON` method, when the object is stringified by `res.json`, they are removed, and the response becomes an empty object. The resources are still being declared and returned by the `declared` method, which I confirmed by adding a `console.log` of the returned object. While investigating however, I did find a related issue - by default the `declare` method uses the name of the class as the name of the resource being declared. This is problematic as the class name is mangled by esbuild during the bundling and minification process. This can easily be solved by declaring the resources with an explicit name (i.e. `SCIMMY.Resources.declare(SCIMMY.Resources.User, "User")`).

Third was going to be about instantiating the resource classes before calling the read method, but you identified that yourself 🙂.

Finally, I wondered whether you had seen related the [scimmy-routers](https://github.com/scimmyjs/scimmy-routers) package? It uses SCIMMY to implement the SCIM endpoints as express middleware, and does a fair bit of the heavy lifting around configuration that you're currently handling in your initialisation method.

Thanks,
Sam
