### ISSUE TITLE
Issue with string type patch values when another type is expected integrating with Microsoft Entra ID

### ISSUE THREAD

**Issue by arxssoftware** [scimmyjs/scimmy#51]
We ran into following issue when integrating with Microsoft Entra ID Provisioning Service:

`Attribute 'active' expected value type 'boolean' but found type 'string' for 'replace' op of operation 1 in PatchOp request body`

This error happened due to a malformed PATCH request:

```jsonc
// PATCH /scim/v2/Users/1234567-1234-1234-1234-123456789012
{
  schemas: [ 'urn:ietf:params:scim:api:messages:2.0:PatchOp' ],
  Operations: [
    { op: 'Replace', path: 'active', value: 'False' }
  ]
}
```
I imagine the value here is supposed to be the boolean value `false`, but Entra ID serializes json patch values as strings.

Would it be possible/desirable to support the type checker either, not flagging this, either automatically converting to the desired type?

**Comment by arxssoftware** [comment]
As a workaround we're modifying the request body before it gets passed to the SCIMMYRouters handler:

    // Run this before your middleware so the request body is available
    app.use(express.json({ type: ["application/scim+json", "application/json"], limit: "1mb" }));
    app.use("/scim/v2", (req, res, next) => {
        if (req.method == "PATCH" && req.body && Array.isArray(req.body.Operations)) {
            const { body } = req;
    
            req.body.Operations = body.Operations
                .map(x => ({
                    ...x,
                    value: sanitizeValue(x.path, x.value)
                }));
        }
        next();
    });

**Comment by sleelin** [comment]
Hi @arxssoftware, thanks for getting in touch.
According to [this Microsoft article](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/application-provisioning-config-problem-scim-compatibility#scim-20-compliance-issues-and-status) regarding Entra ID SCIM protocol compliance issues, and the ["Disable User" example request](https://learn.microsoft.com/en-us/entra/identity/app-provisioning/use-scim-to-provision-users-and-groups#disable-user) from their "plan provisioning" tutorial, I had been lead to believe that Microsoft had rolled out a fix for this issue as far back as 2018. Further investigation shows that [the fix is still stuck behind a "feature flag"](https://learn.microsoft.com/en-us/answers/questions/1328467/scim-patch-azure-ad-sends-string-value-for-active). The flag must be manually enabled by adding the string `?aadOptscim062020` to the end of the tenant URL, which supposedly corrects the behaviour of booleans in PATCH operations, but disables the "On-Demand Provisioning" functionality.

Whilst investigating I also came across [this StackOverflow answer](https://stackoverflow.com/a/59673783) in which the author details instructions for modifying the `active` attribute mapping in Entra ID to correctly map the values into boolean in PATCH operations and resolve the issue.

I'm hesitant to add explicit handling to accomodate this non-compliant behaviour when other solutions may be available, however I would consider it if no other alternative works. If possible, would you mind testing to see whether either adding the feature flag to the tenant URL or modifying the attribute mapping result in Entra ID sending compliant PATCH requests?
If not, the middleware you added will of course also resolve the issue, but it would be much nicer if Entra ID was sending compliant requests and it was not necessary 🙂

Thanks,
Sam

**Comment by arxssoftware** [comment]
Hi Sam, 

Thanks for that thorough investigation!. I agree with your conclusion. Adding explicit support for non-compliant behavior does seem like it could do more harm than good. 

That said, in our sitaution, we are just going to take the pragmatic route and keep the middleware. As this reduces the amount of support requests we need to handle ;-)

Thanks again!
Yannick
