### ISSUE TITLE
Q: How to acquire request context in Resources.ingress/egress/degress?

### ISSUE THREAD

**Issue by upirr** [scimmyjs/scimmy#6]
Some background: we're considering using Scimmy to implement API  for SCIM Provisioning in OKTA. Our user structure approximately looks like this: Workspace <-1-M-> Group <-M-M-> User. 

This means that different organizations (read Workspaces) might wanna use different OKTA accounts to sync their users with our system. Problem is that during authentication it is known what workspace incoming request is originating from, but when request is passed down to ingress/egress/degress the context is lost, there's no way to identify which workspace should i use to list users from.

Is there any way to pass a context to Resource instance methods? I understand that this issue is in intersection between scimmy-routers and scimmy.

**Comment by sleelin** [comment]
Not directly, as by design, SCIMMY doesn't have any knowledge of the underlying request (so it's not tied to any specific HTTP server dependencies). You might be able to achieve this by extending the User resource with the EnterpriseUser schema, then in the authentication handler method provided to scimmy-routers, you could manipulate the request body by setting the authenticated workspace details (e.g. the workspace's ID or other uniquely identifying piece of information) as the value of the EnterpriseUser's organization attribute, which will be passed through to the resource.

Thanks for reaching out!
Let me know if this works for you, or if I can assist you with anything else.

**Comment by upirr** [comment]
Thank you for a quick reply. I took a brief look at it. Ok, i could definitely extend the User, but problem is i see no room for passing additional context to extended User. Here's a simplest route in Resources router in scimmy-routers:
```
        this.get("/", async (req, res) => {
            try {
                res.send(await new Resource(req.query).read());
            } catch (ex) {
                res.status(ex.status ?? 500).send(new SCIMMY.Messages.Error(ex));
            }
        });
```

How'd i pass additional information i extended User with? The only possible way i see is via static properties on Resource, but i don't see this approach as being reliable in a slightest. That is of course assuming i'll be using both scimmy and scimmy-routers which i'd like to do if possible.

**Comment by jonathanstokes** [comment]
This issue is a bit old, but in case this helps anyone coming here with the same problem, I was able to workaround it using the `express-http-context` library, which is a request-scoped cache.  In my `scimmy-routers` `handler` function I confirm authorization and stash away the identifying info in the `httpContext` and then retrieve it elsewhere before handling ingress/egress calls.
