### ISSUE TITLE
email not working with attributes query anymore

### ISSUE THREAD

**Issue by spech66** [scimmyjs/scimmy#61]
Providing the attributes filter in the 1.3.0 version doesn't return the emails anymore.

GET `?attributes=userName,emails` will only return id and userName.

**Comment by sleelin** [comment]
Hi @spech66, thanks for raising this!
I was able to reproduce the issue and it appears to have been caused by changes introduced in PR #56.
I've now released v1.3.1 which should resolve this issue and return to the expected behaviour of including the entire `emails` attribute value when explicitly specified in the request.

Thanks,
Sam
